# Generated by Django 4.0.4 on 2023-05-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_city_electronic_review_place_place_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic_review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='place_review',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
        migrations.AlterField(
            model_name='place_review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='place_review',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.place'),
        ),
    ]
