# Generated by Django 4.0.4 on 2023-05-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_electronic_review_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_review',
            name='product',
        ),
        migrations.AlterField(
            model_name='place_review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
