# Generated by Django 4.0.4 on 2023-05-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_place_review_product_alter_place_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic_review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
